---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: freemium, professional, essential, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go 
summary: Diversas opções de licenciamento estão disponíveis para Cloud Volumes ONTAP. Cada opção permite que você escolha uma configuração que atenda às suas necessidades. 
---
= Visão geral do licenciamento para Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Diversas opções de licenciamento estão disponíveis para Cloud Volumes ONTAP. Cada opção permite que você escolha um modelo de consumo que atenda às suas necessidades.

As seguintes opções de licenciamento estão disponíveis para novos clientes.

Pacotes de licenciamento baseados em capacidade:: O licenciamento baseado em capacidade permite que você pague pelo Cloud Volumes ONTAP por TiB de capacidade. A licença está associada à sua conta NetApp e permite que você cobre vários sistemas com a licença, desde que haja capacidade suficiente disponível por meio da licença.
+
--
O licenciamento baseado em capacidade está disponível na forma de um pacote. Ao implantar um sistema Cloud Volumes ONTAP, você pode escolher entre diversos pacotes de licenciamento com base nas necessidades do seu negócio.

--


https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#packages["Pacotes"^] https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing-charging.html["Mais informações sobre licenças baseadas em capacidade"^]

Keystone Flex Subscription:: Um serviço de assinatura com pagamento conforme o uso, que oferece uma experiência de nuvem híbrida perfeita para quem prefere OpEx modelos de consumo em vez de CapEx antecipado ou leasing.
+
--
A cobrança é baseada no tamanho da sua capacidade contratada para um ou mais pares de HA do Cloud Volumes ONTAP em sua assinatura Keystone Flex.

--


O modelo de licenciamento por nó anterior continua disponível para clientes existentes que já adquiriram uma licença ou que possuem uma assinatura ativa no marketplace.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Saiba mais sobre essas opções de licenciamento"^]
