---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: As limitações conhecidas identificam plataformas, dispositivos ou funções que não são compatíveis com esta versão do produto ou que não interoperam corretamente com ela. Analise essas limitações cuidadosamente. 
---
= Limitações conhecidas do Cloud Volumes ONTAP em todos os provedores de nuvem
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As limitações conhecidas identificam plataformas, dispositivos ou funções que não são compatíveis com esta versão do produto ou que não interoperam corretamente com ela. Analise essas limitações cuidadosamente.

As seguintes limitações se aplicam ao Cloud Volumes ONTAP em todos os provedores de nuvem: AWS, Azure e Google Cloud.



== Recursos ONTAP não suportados

Os seguintes recursos não são compatíveis com Cloud Volumes ONTAP:

* Desduplicação em linha no nível de agregado
* Desduplicação em segundo plano no nível de agregado
* Centro de manutenção de disco
* Higienização de disco
* FabricPool espelhamento
* Fibre Channel (FC)
* Flash Pools
* Infinite Volumes
* Grupos de interface
* Failover de LIF intranode
* MetroCluster
* Verificação de múltiplos administradores
+
Habilitar a verificação multiadministrador no Cloud Volumes ONTAP resultará em uma configuração não suportada.

* RAID4, RAID-DP, RAID-TEC (RAID0 é suportado)
* Processador de serviço
* SnapLock Compliance e Enterprise modes (somente Cloud WORM é compatível)
* SnapMirror Síncrono
* VLANs
* Disponibilidade Contínua (CA) do SMB
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Compartilhamentos SMB continuamente disponíveis"^] para operações não disruptivas não são suportadas.





== Operações máximas de replicação simultâneas

O número máximo de transferências simultâneas de SnapMirror ou SnapVault para Cloud Volumes ONTAP é 100 por nó, independentemente do tipo de instância ou tipo de máquina.



== Snapshots do provedor de nuvem não devem ser usados para seus planos de backup e recuperação

Você não deve usar snapshots do seu provedor de nuvem como parte do seu plano de backup e recuperação para dados do Cloud Volumes ONTAP. Você deve sempre usar cópias de Snapshot do ONTAP ou soluções de backup de terceiro para fazer backup e restaurar dados hospedados no Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["Aprenda a usar NetApp Backup and Recovery para fazer backup e restaurar dados do ONTAP"^].


NOTE: Os pontos de consistência do ONTAP no sistema de arquivos WAFL determinam a consistência de dados. Somente o ONTAP pode colocar o sistema de arquivos WAFL em estado de espera para criar um backup consistente com falhas.



== Cloud Volumes ONTAP suporta apenas instâncias de VM reservadas e sob demanda

Cloud Volumes ONTAP pode ser executado em uma instância de VM reservada ou sob demanda do seu provedor de nuvem. Outros tipos de instâncias de VM não são suportados.



== Não se devem usar soluções automáticas de gerenciamento de recursos de aplicativos

Soluções automáticas de gerenciamento de recursos de aplicativos não devem gerenciar sistemas Cloud Volumes ONTAP. Fazer isso pode resultar em uma alteração para uma configuração não suportada. Por exemplo, a solução pode alterar Cloud Volumes ONTAP para um tipo de instância de máquina virtual não suportado.



== As atualizações de software devem ser concluídas pelo NetApp Console

As atualizações do Cloud Volumes ONTAP devem ser concluídas a partir do NetApp Console. Você não deve atualizar o Cloud Volumes ONTAP usando o System Manager ou a CLI. Fazer isso pode afetar a estabilidade do sistema.



== A implantação do Cloud Volumes ONTAP não deve ser modificada a partir do console do seu provedor de nuvem

Alterações em uma configuração do Cloud Volumes ONTAP feitas pelo console do seu provedor de nuvem resultam em uma configuração não suportada. Quaisquer alterações nos recursos do Cloud Volumes ONTAP que o Console cria e gerencia podem impactar a estabilidade do sistema e a capacidade do Console de gerenciar o sistema.


NOTE: Após a implantação inicial, a modificação do nome da assinatura do Azure usada para os recursos do Cloud Volumes ONTAP é suportada.



== Os discos e agregados devem ser gerenciados a partir do Console

Todos os discos e agregados devem ser criados e excluídos diretamente do Console. Você não deve executar essas ações a partir de outra ferramenta de gerenciamento. Fazer isso pode afetar a estabilidade do sistema, dificultar a adição de discos no futuro e potencialmente gerar taxas redundantes do provedor de nuvem.



== SnapManager limitação de licenciamento

SnapManager por servidor são suportadas com Cloud Volumes ONTAP. Licenças por sistema de storage (SnapManager suite) não são suportadas.



== Limitações com agentes e extensões de terceiro

Agentes de terceiros e extensões de máquina virtual não são suportados em instâncias de máquina virtual do Cloud Volumes ONTAP.
