---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.17.1 inclui um novo aprimoramento. 
---
= Novidades no Cloud Volumes ONTAP 9.17.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.17.1 inclui novos aprimoramentos.

Novos recursos do Cloud Volumes ONTAP também foram introduzidos nas versões mais recentes do NetApp Console. Para obter mais informações, consulte as novidades em  https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^] managed no Console.



== 9.17.1 P5 (23 de março de 2026)

O patch P5 do Cloud Volumes ONTAP 9.17.1 já está disponível para atualização na AWS, Azure e Google Cloud. O Console solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P5["Veja a lista de bugs corrigidos no patch P5"^] (NetApp site de suporte, é necessário login).



== 9.17.1 P4 (17 de fevereiro de 2026)

O patch P4 do Cloud Volumes ONTAP 9.17.1 já está disponível para atualização na AWS, Azure e Google Cloud. O Console solicitará que você atualize seus sistemas existentes para este patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P4["Veja a lista de bugs corrigidos no patch P4"^] (NetApp site de suporte, é necessário login).



== 9.17.1 P3 (22 de dezembro de 2025)

O patch P3 do Cloud Volumes ONTAP 9.17.1 já está disponível para atualização na AWS, Azure e Google Cloud. O Console solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P3["Veja a lista de bugs corrigidos no patch P3"^] (NetApp site de suporte, é necessário login).



== 9.17.1 P2 (04 de dezembro de 2025)

O patch P2 do Cloud Volumes ONTAP 9.17.1 já está disponível para atualização na AWS, Azure e Google Cloud. O Console solicitará que você atualize seus sistemas existentes para esta versão de patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P2["Veja a lista de bugs corrigidos no patch P2"^] (NetApp site de suporte, login necessário).



== 9.17.1 P1 (04 de novembro de 2025)

O patch 9.17.1 P1 do Cloud Volumes ONTAP já está disponível para implantação e atualização na AWS, Azure e Google Cloud. O Console solicitará que você atualize seus sistemas existentes para este patch.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P1["Veja a lista de bugs corrigidos no patch P1"^] (NetApp site de suporte, é necessário login).



== Notas de atualização

Leia estas notas para saber mais sobre a atualização para esta versão.



=== Como atualizar

As atualizações do Cloud Volumes ONTAP devem ser concluídas a partir do Console. Você não deve atualizar Cloud Volumes ONTAP usando System Manager ou a CLI. Fazer isso pode afetar a estabilidade do sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Aprenda como atualizar quando o Console notificar você"^].



=== Caminho de atualização compatível

Você pode atualizar para o Cloud Volumes ONTAP 9.17.1 P1 a partir da versão 9.16.1 na AWS, Azure e Google Cloud. O Console solicitará que você atualize os sistemas Cloud Volumes ONTAP elegíveis para esta versão.



=== Tempo de inatividade

* A atualização de um sistema de nó único deixa o sistema offline por até 25 minutos, durante os quais a E/S é interrompida.
* A atualização de um par de HA é não disruptiva e a E/S não é interrompida. Durante esse processo de atualização não disruptiva, cada nó é atualizado em conjunto para continuar fornecendo E/S aos clientes.

